name: diamnow
description: Diamond app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk:  ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.4
  carousel_slider: ^3.0.0
  retrofit: 1.3.4
  event_bus: ^1.1.0
  provider : ^4.0.5
  kiwi: 2.0.0
  fluttertoast: ^6.0.1
  flutter_spinkit: ^4.0.0
  pull_to_refresh: 1.6.3
  dots_indicator: ^1.0.0
  intl: any
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  flushbar:  1.10.4
  flutter_html: any
  flare_flutter: ^1.6.1
  path_provider: ^1.3.0
  flutter_files_picker:
    path: ./FilePicker
  logs:
    git: https://github.com/pq/logs
  dashed_container: ^1.0.1
  sembast: ^1.15.1
  rxbus: any
  percent_indicator: ^2.1.3
  onesignal_flutter: any
  # permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  app_settings: ^4.0.0
  package_info: ^0.4.0+16
  store_redirect: ^1.0.2
  compressimage: 0.1.1
  flutter_exif_rotation: ^0.2.7
  sms_autofill: ^1.2.5
  unique_identifier: ^0.0.3
  lottie: any
  image: any
  country_pickers: ^1.3.0
  flutter_statusbarcolor: ^0.2.3
  libphonenumber: ^1.0.1
  custom_localization:
     git: https://gitlab.coruscate.in:8443/coruslab/flutter-localisation.git
  encrypt: ^4.0.0
  webview_flutter: 1.0.7
  material_segmented_control: ^2.1.0+1
  url_launcher: ^5.7.2
  flutter_tags: ^0.4.9
  flutter_slidable: ^0.5.7
  linked_scroll_controller: ^0.1.2
  share: ^0.6.5+4
  syncfusion_flutter_datepicker: ^18.3.44-beta
  flutter_time_picker_spinner: 1.0.6+1
  scrollable_positioned_list: ^0.1.8
  flutter_money_formatter: any
  permission_handler: ^4.4.0+hotfix.2
  gallery_saver: ^2.0.1
  downloads_path_provider: ^0.1.0
  # flutter_launch: ^0.2.0
  # open_file: ^3.0.3
  local_auth: ^0.5.2+3
  #flutter_lock_screen: ^1.0.8
  # speech_recognition: ^0.3.0+1
  # permission_handler: ^3.2.0
  marquee: ^1.6.1
  smooth_page_indicator: ^0.2.0
  speech_to_text: ^3.1.0
  photo_view: ^0.10.2
  firebase_analytics: ^6.3.0
  flutter_cache_manager: any
  # flutter_tags: ^0.1.9
  flutter_local_notifications: any
  uuid: ^2.2.2
  collection: ^1.14.13
  screenshot_callback: any
  flutter_device_type: ^0.3.2
  flutter_native_timezone: ^1.0.4
  flick_video_player: any
  flutter_widgets: 0.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  kiwi_generator: 2.0.0
  build_runner: any
  retrofit_generator: 1.3.4
  custom_localization_generator:
    git:
      url: https://gitlab.coruscate.in:8443/coruslab/flutter-localisation.git
      path: custom_localization_generator

# dependency_overrides:
#   analyzer: '0.39.11'

module:
  androidX: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/diamnow/
    - assets/auth/
    - assets/Json/
    - assets/fonts/
    - assets/shape/
    - assets/filter/
    - assets/more/
    - assets/DiamondDetail/
    - assets/Common/
    - assets/drawer/
    - assets/PlaceHolder/
    - assets/Home/
    - assets/Share/
    - assets/PNShah/
    - assets/PNShah/ForgetMPIN/

    #Overlay screens
    - assets/Overlay/Home/
    - assets/Overlay/MyAccount/
    - assets/Overlay/Search/
    - assets/Overlay/SearchResult/
    - assets/Overlay/DiamondDetail/
    - assets/Overlay/CompareStone/
    - assets/Overlay/Offer/
    - assets/chls.pem


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 800
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 600
        - asset: assets/fonts/Avenir-Roman.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
        
       
