name: diamnow
description: Diamond app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk:  ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.4
  retrofit: 1.3.4
  event_bus: ^1.1.0
  provider: ^3.1.0
  kiwi: 2.0.0
  fluttertoast: ^6.0.1
  flutter_spinkit: ^4.0.0
  pull_to_refresh: ^1.5.6
  dots_indicator: ^1.0.0
  intl: ^0.16.0
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  flushbar:  1.10.4
  flutter_html: any
  flare_flutter: ^1.6.1
  path_provider: ^1.3.0

  flutter_files_picker:
    path: ./FilePicker
  logs:
    git: https://github.com/pq/logs
  dashed_container: ^1.0.1
  sembast: ^1.15.1
  rxbus: any
  # percent_indicator: ^2.1.3
  # onesignal_flutter: 2.3.4
  # permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  app_settings: ^4.0.0
  package_info: ^0.4.0+16
  store_redirect: ^1.0.2
  compressimage: 0.1.1
  flutter_exif_rotation: ^0.2.7
  sms_autofill: ^1.2.5
  unique_identifier: ^0.0.3
  lottie: any
  image: any
  country_pickers: ^1.3.0
  flutter_statusbarcolor: ^0.2.3
  libphonenumber: ^1.0.1
  custom_localization:
    path: ./custom_localization
  encrypt: ^4.0.0
  webview_flutter: ^1.0.5
  material_segmented_control: ^2.1.0+1
  url_launcher: ^5.7.2
  flutter_tags: ^0.4.9
  flutter_slidable: ^0.5.7
  linked_scroll_controller: ^0.1.2
  share: 0.6.4+3
  syncfusion_flutter_datepicker: ^18.3.44-beta
  flutter_time_picker_spinner: 1.0.6+1
  # flutter_tags: ^0.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  kiwi_generator: 2.0.0
  build_runner: any
  retrofit_generator: 1.3.4
  custom_localization_generator:
    path: ./custom_localization/custom_localization_generator

# dependency_overrides:
#   analyzer: '0.39.11'




flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/diamnow/
    - assets/auth/
    - assets/Json/
    - assets/fonts/
    - assets/shape/
    - assets/filter/
    - assets/more/
    - assets/DiamondDetail/
    - assets/Common/
    - assets/drawer/
    - assets/PlaceHolder/
    - assets/Home/
      #- assets/chls/hochls.pem
    # - assets/chls.pem


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/avenirltstd-light.otf
          weight: 300
        - asset: assets/fonts/Avenir-Medium.otf
          weight: 500
